# Nome da pipeline
name: Build and Push Docker Image

# Gatilhos para iniciar a pipeline
trigger:
- main

# Pool de agentes para executar a pipeline
pool:
  vmImage: 'ubuntu-latest'

# Variáveis (opcional, para customizar nomes de repositório, tags, etc.)
variables:
  dockerRepo: 'sysyphus/unyleya_projeto_devops'
  dockerImageTag: '$(Build.BuildId)'

# Etapas da pipeline
steps:

- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'dockerhub'  # Nome da sua conexão de serviço

- task: Docker@2
  displayName: 'Build and Push Image'
  inputs:
    command: buildAndPush
    repository: $(dockerRepo)
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile' 
    tags: |
      $(dockerImageTag)
      latest
